export { strapiUrl, client } from "./client"
export type { JobOffer } from "./job-offers"
export { fetchJobOffers, fetchJobOffer, fetchMyJobOffers } from "./job-offers"
export type { Event } from "./events"
export { fetchEvents, fetchEvent, updateEvent, deleteEvent, fetchMyEvents } from "./events"
export type { MapLocation } from "./locations"
export { fetchLocations } from "./locations"
export type { StudentGroup } from "./student-groups"
export { fetchStudentGroups } from "./student-groups"
export type { MensaMeal } from "./mensa"
export { fetchMensaMeals } from "./mensa"
