export const JOB_OFFERS = [
  {
    title: "Frontend Developer",
    company: "TechCorp GmbH",
    location: "Bamberg",
    working_hours: 40,
    description: "We are looking for an experienced Frontend Developer to join our team.",
    online_status: "published",
    external_url: "https://example.com/apply/frontend",
    contact: { name: "Anna Müller", mail: "anna@techcorp.de", phone: "+49 951 123456" },
  },
  {
    title: "Backend Engineer",
    company: "DataSystems AG",
    location: "Remote",
    working_hours: 32,
    description: "Join our backend team and help build scalable APIs.",
    online_status: "published",
    contact: { name: "Max Schmidt", mail: "max@datasystems.de" },
  },
  {
    title: "UX Designer",
    company: "Kreativ Studio",
    location: "Bamberg",
    working_hours: 20,
    description: "Part-time UX Designer for a creative agency in Bamberg.",
    online_status: "submitted",
    contact: { name: "John Doe", mail: "jobs@kreativstudio.de" },
  },
  {
    title: "DevOps Engineer",
    company: "CloudOps GmbH",
    location: "Nürnberg",
    working_hours: 40,
    description: "Maintain and improve our cloud infrastructure.",
    online_status: "expired",
    contact: { name: "Lisa Weber", mail: "lisa@cloudops.de" },
  },
  {
    title: "Full Stack Developer",
    company: "Startup Hub Bamberg",
    location: "Bamberg",
    working_hours: 40,
    description:
      "Join our fast-growing startup and work across the entire stack — React, Node.js, and PostgreSQL.",
    online_status: "published",
    external_url: "https://example.com/apply/fullstack",
    contact: { name: "Tom Bauer", mail: "tom@startuphub.de", phone: "+49 951 654321" },
  },
  {
    title: "Werkstudent Marketing",
    company: "RegioMedia GmbH",
    location: "Bamberg",
    working_hours: 20,
    description:
      "Unterstütze unser Marketingteam bei der Erstellung von Content und der Pflege unserer Social-Media-Kanäle.",
    online_status: "published",
    contact: { name: "Sara König", mail: "sara@regiomedia.de" },
  },
] as const
