export const mockApiResponse = {
  menu: [
    {
      year: 2026,
      week_number: 15,
      menu_per_day: {
        "1": {
          day: "2026-04-06",
          menu_entries: null,
          empty_notices: [{ message: "Feiertags geschlossen." }],
        },
        "2": {
          day: "2026-04-07",
          menu_entries: [
            {
              name: "Karottencremesuppe mit ger\u00f6steten Sonnenblumenkernen",
              price: 1.5,
              price_servant: 1.6,
              price_guest: 1.8,
              food: 9194,
              food_type: ["v"],
              additives: ["z1", "a1", "a9", "a15", "a17"],
            },
            {
              name: 'Spaghetti "Aglio Olio" mit Chili & Knoblauch in Oliven\u00f6l und griebenem Grana Padano',
              price: 2.8,
              price_servant: 4.15,
              price_guest: 5.1,
              food: 9111,
              food_type: ["fl"],
              additives: ["z1", "z2", "z3", "z5", "a1", "a7", "a12", "a15", "k"],
            },
            {
              name: 'Mildes "Thai Curry" in Kokosmilch mit frischem Gem\u00fcse, Lotuswurzeln & Zitronengras dazu Fair Trade Basmati Reis',
              price: 3.65,
              price_servant: 5.0,
              price_guest: 5.95,
              food: 9015,
              food_type: ["v"],
              additives: ["z2", "z3", "a6", "a12"],
            },
            {
              name: "H\u00e4hnchenschnitzel im Knuspermantel mit Super Crunch Pommes frites",
              price: 4.35,
              price_servant: 5.8,
              price_guest: 6.75,
              food: 9014,
              food_type: ["g"],
              additives: ["a1", "a15", "a17", "g"],
            },
          ],
          empty_notices: null,
        },
        "3": {
          day: "2026-04-08",
          menu_entries: [
            {
              name: "Cremesuppe mit frischem B\u00e4rlauch und Croutons",
              price: 1.5,
              price_servant: 1.6,
              price_guest: 1.8,
              food: 9193,
              food_type: ["fl"],
              additives: ["z1", "a1", "a7", "a9", "a15", "a17"],
            },
            {
              name: '"Hot and Spicy" - Quinoa Chili Burger mit feurigen Jalape\u00f1os und Salsadip',
              price: 3.65,
              price_servant: 5.0,
              price_guest: 5.95,
              food: 9122,
              food_type: ["v"],
              additives: ["z9", "a1", "a9", "a10", "a11", "a12", "a15"],
            },
            {
              name: "Gebratene Schupfnudeln mit knackigen Gem\u00fcse und frischem B\u00e4rlauch",
              price: 3.8,
              price_servant: 5.2,
              price_guest: 6.15,
              food: 9125,
              food_type: ["fl"],
              additives: ["z1", "z3", "a1", "a3", "a9", "a15"],
            },
            {
              name: "H\u00e4hnchen Kebab mit hausgemachtem Tsatsiki gebackene Patatas",
              price: 4.85,
              price_servant: 6.3,
              price_guest: 7.25,
              food: 9123,
              food_type: ["g"],
              additives: ["a6", "a7", "k", "g"],
            },
          ],
          empty_notices: null,
        },
        "4": {
          day: "2026-04-09",
          menu_entries: [
            {
              name: "mensaVital: Veganer Kokos - Milchreis mit Mangoragout dazu einen Rote Bete Salat",
              price: 3.35,
              price_servant: 4.7,
              price_guest: 5.65,
              food: 9133,
              food_type: ["v"],
              additives: ["z1", "z3", "z9", "z12", "a1", "a12", "a18"],
            },
            {
              name: 'Gebratene Mienudeln "Asia Style" mit frischem Gem\u00fcse & Koriander, sweet Chili Dip & Erdn\u00fcssen',
              price: 3.35,
              price_servant: 4.7,
              price_guest: 5.65,
              food: 9136,
              food_type: ["v"],
              additives: ["z2", "z3", "a1", "a5", "a6", "a9", "a11", "a15", "k"],
            },
            {
              name: '"Allg\u00e4uer K\u00e4sesp\u00e4tzle" mit Emmentaler & Bergk\u00e4se \u00fcberbacken dazu R\u00f6stzwiebeln',
              price: 3.65,
              price_servant: 5.0,
              price_guest: 5.95,
              food: 8873,
              food_type: ["fl"],
              additives: ["z1", "a1", "a3", "a7", "a9", "a15", "a17"],
            },
          ],
          empty_notices: null,
        },
        "5": {
          day: "2026-04-10",
          menu_entries: [
            {
              name: "Blumenkohl K\u00e4secremesuppe",
              price: 1.5,
              price_servant: 1.6,
              price_guest: 1.8,
              food: 9192,
              food_type: ["fl"],
              additives: ["z1", "a1", "a7", "a9", "a15", "a17"],
            },
            {
              name: "Tajine von frischen Gem\u00fcse, frischem Koriander mit Sumach, Fladenbrot & orientalischer Minz Joghurt Dip",
              price: 3.65,
              price_servant: 5.0,
              price_guest: 5.95,
              food: 9146,
              food_type: ["fl"],
              additives: ["a1", "a7", "a9", "a12", "a15", "k"],
            },
            {
              name: "Gebackene Brokkoli - Nuss - Knusperecke mit Tomatenreis",
              price: 3.1,
              price_servant: 4.45,
              price_guest: 5.4,
              food: 9147,
              food_type: ["v"],
              additives: ["a1", "a8", "a12", "a15", "a18", "a19", "a20", "k"],
            },
            {
              name: "Gebratenes Filet vom Nordmeerseelachs B\u00e4rlauchso\u00dfe Kartoffelr\u00f6sti",
              price: 5.15,
              price_servant: 6.6,
              price_guest: 7.55,
              food: 9148,
              food_type: ["f"],
              additives: ["z1", "a1", "a4", "a7", "a8", "a9", "a15", "a17", "a19", "f"],
            },
          ],
          empty_notices: null,
        },
      },
    },
    {
      year: 2026,
      week_number: 16,
      menu_per_day: {
        "1": {
          day: "2026-04-13",
          menu_entries: [
            {
              name: "Tomatensuppe mit frischem Basilikum",
              price: 1.5,
              price_servant: 1.6,
              price_guest: 1.8,
              food: 9191,
              food_type: ["v"],
              additives: ["z1", "a1", "a12", "a15", "k"],
            },
            {
              name: "Kartoffeltaschen gef\u00fcllt mit Tomaten & Mozzarella dazu B\u00e4rlauch Pappardelle",
              price: 3.8,
              price_servant: 5.2,
              price_guest: 6.15,
              food: 9178,
              food_type: ["fl"],
              additives: ["a1", "a3", "a7", "a8", "a15", "a19"],
            },
            {
              name: "Orientalische Gem\u00fcspfanne mit Okraschoten & Berberitzen auf Fladenbrot dazu veganer Tandoori Dip",
              price: 4.35,
              price_servant: 5.8,
              price_guest: 6.75,
              food: 9177,
              food_type: ["v"],
              additives: ["z2", "z3", "a1", "a11", "a12", "k"],
            },
            {
              name: "Currywurst vom Grill mit Super Crunch Pommes frites",
              price: 4.1,
              price_servant: 5.5,
              price_guest: 6.45,
              food: 9179,
              food_type: ["r", "s"],
              additives: ["z1", "z2", "z3", "z8", "z9", "a9", "a10", "a12", "r", "s"],
            },
          ],
          empty_notices: null,
        },
        "2": {
          day: "2026-04-14",
          menu_entries: [
            {
              name: "Spargelcremesuppe - aus frischem fr\u00e4nkischen Spargel",
              price: 1.5,
              price_servant: 1.6,
              price_guest: 1.8,
              food: 9190,
              food_type: ["fl"],
              additives: ["z1", "a1", "a7", "a9", "a15", "a17"],
            },
            {
              name: "Ofenkartoffeln mit hausgemachtem B\u00e4rlauchquark",
              price: 2.6,
              price_servant: 3.9,
              price_guest: 4.85,
              food: 9168,
              food_type: ["fl"],
              additives: ["a7", "a8", "a19"],
            },
            {
              name: "Gebratener Reis mit knackigen Wokgem\u00fcse, Cashewnuts, frischem Koriander, Chili und Sojasprossen",
              price: 3.35,
              price_servant: 4.7,
              price_guest: 5.65,
              food: 9170,
              food_type: ["v"],
              additives: ["z2", "z3", "a1", "a6", "a8", "a9", "a11", "a15", "a22", "k"],
            },
            {
              name: 'Spaghetti "alla Bolognese" aus reinem frischen Rinderhackfleisch & griebenen Grana Padano',
              price: 4.45,
              price_servant: 5.9,
              price_guest: 6.85,
              food: 8710,
              food_type: ["r"],
              additives: ["z2", "a1", "a7", "a9", "a15", "k", "r"],
            },
          ],
          empty_notices: null,
        },
        "3": {
          day: "2026-04-15",
          menu_entries: [
            {
              name: "Cremesuppe mit frischem B\u00e4rlauch und Croutons",
              price: 1.5,
              price_servant: 1.6,
              price_guest: 1.8,
              food: 9193,
              food_type: ["v"],
              additives: ["z1", "a1", "a9", "a15", "a17"],
            },
            {
              name: 'Penne "al Arrabbiata" in feuriger Tomaten Peperonata So\u00dfe & veganem Reibk\u00e4se',
              price: 2.8,
              price_servant: 4.15,
              price_guest: 5.1,
              food: 9201,
              food_type: ["v"],
              additives: ["z1", "z3", "z5", "a1", "a12", "a15", "k"],
            },
            {
              name: "Ofenfrischer Krustenbraten in Bierso\u00dfe mit Kartoffelklo\u00df",
              price: 3.8,
              price_servant: 5.2,
              price_guest: 6.15,
              food: 9202,
              food_type: ["s"],
              additives: [
                "z1",
                "z2",
                "z3",
                "z5",
                "a1",
                "a9",
                "a10",
                "a12",
                "a15",
                "a16",
                "a17",
                "a18",
                "s",
              ],
            },
            {
              name: 'Gebackene Fr\u00fchlingsrolle mit Sweet Chili So\u00dfe Gebratene Mienudeln "Asia Style"',
              price: 4.1,
              price_servant: 5.5,
              price_guest: 6.45,
              food: 9200,
              food_type: ["fl"],
              additives: ["a1", "a3", "a6", "a9", "a11", "a15"],
            },
            {
              name: "Frischer Spargel vom fr\u00e4nkischen Spargelbauer Kartoffeln mit frischem B\u00e4rlauch",
              price: 5.15,
              price_servant: 6.6,
              price_guest: 7.55,
              food: 9166,
              food_type: [""],
              additives: ["z1", "a1", "a3", "a7", "a9", "a12", "a15", "a17"],
            },
          ],
          empty_notices: null,
        },
        "4": {
          day: "2026-04-16",
          menu_entries: [
            {
              name: "Kartoffelrahms\u00fcppchen mit Wurzelgem\u00fcse",
              price: 1.5,
              price_servant: 1.6,
              price_guest: 1.8,
              food: 9195,
              food_type: ["v"],
              additives: ["a7", "a9"],
            },
            {
              name: '"Mac and Cheese" \u00fcberbackene Nudeln in kr\u00e4ftiger Cheddar K\u00e4seso\u00dfe',
              price: 2.8,
              price_servant: 4.15,
              price_guest: 5.1,
              food: 9217,
              food_type: ["fl"],
              additives: ["z1", "z2", "a1", "a6", "a7", "a9", "a15", "a17", "k"],
            },
            {
              name: "Gnocchi aus der Pfanne mit frischem B\u00e4rlauch und Kirschtomaten",
              price: 3.35,
              price_servant: 4.7,
              price_guest: 5.65,
              food: 9215,
              food_type: ["v"],
              additives: ["a1", "a15", "k"],
            },
            {
              name: "mensaVital: Veganes Soja Gem\u00fcse Chili mit Bohnen und Tacos dazu Kr\u00e4uterreis",
              price: 3.1,
              price_servant: 4.45,
              price_guest: 5.4,
              food: 9218,
              food_type: ["v"],
              additives: ["z1", "a1", "a6", "a9", "a15", "k"],
            },
          ],
          empty_notices: null,
        },
        "5": {
          day: "2026-04-17",
          menu_entries: [
            {
              name: "Japanische Misosuppe mit Seealgen, frischem Gem\u00fcse, Koriander & Tofuw\u00fcrfeln",
              price: 1.5,
              price_servant: 1.6,
              price_guest: 1.8,
              food: 9226,
              food_type: ["v"],
              additives: ["z1", "z2", "z3", "a1", "a6", "a9", "a11", "a12", "a15", "k"],
            },
            {
              name: 'Tortelloni "Verdure Mediterraneo" Tomaten Pestoso\u00dfe',
              price: 3.35,
              price_servant: 4.7,
              price_guest: 5.65,
              food: 9225,
              food_type: ["v"],
              additives: ["z1", "a1", "a8", "a9", "a15", "a17", "a18", "a22", "k"],
            },
            {
              name: '"Nasi Goreng" gebratener Reis mit Ei, knackigem Wokgem\u00fcse, H\u00e4hnchen, Garnelen & frischem Koriander',
              price: 4.1,
              price_servant: 5.5,
              price_guest: 6.45,
              food: 9227,
              food_type: ["g", "f"],
              additives: [
                "z2",
                "z3",
                "z8",
                "a1",
                "a2",
                "a3",
                "a6",
                "a8",
                "a9",
                "a11",
                "a15",
                "a22",
                "k",
                "g",
                "f",
              ],
            },
            {
              name: "Rahmspinat mit R\u00fchrei Salzkartoffeln",
              price: 4.1,
              price_servant: 5.5,
              price_guest: 6.45,
              food: 9228,
              food_type: ["fl"],
              additives: ["z1", "a1", "a3", "a7", "a9", "a12", "a15", "a17"],
            },
          ],
          empty_notices: null,
        },
      },
    },
  ],
  trimmings: [
    { name: "Side Dishes", price: 1.3, price_servant: 1.4, price_guest: 1.6 },
    { name: "Dessert (small)", price: 1.3, price_servant: 1.4, price_guest: 1.6 },
    { name: "Dessert (big)", price: 1.5, price_servant: 1.6, price_guest: 1.8 },
  ],
  food_types: [
    { identifier: "s", name: "pork", label: "Pork" },
    { identifier: "r", name: "beef", label: "Beef" },
    { identifier: "k", name: "calf", label: "Calf" },
    { identifier: "l", name: "lamb", label: "Lamb" },
    { identifier: "f", name: "fish", label: "Fish" },
    { identifier: "w", name: "venison", label: "Venison" },
    { identifier: "g", name: "poultry", label: "Poultry" },
    { identifier: "fl", name: "meatless", label: "Meatless" },
    { identifier: "vs", name: "shoulderOfHam", label: "Shoulder of Ham" },
    { identifier: "a", name: "alcohol", label: "Alcohol" },
    { identifier: "v", name: "vegan", label: "Vegan" },
  ],
  additives: [
    { identifier: "z1", name: "dye", label: "mit Farbstoff" },
    { identifier: "z2", name: "preserved", label: "konserviert" },
    { identifier: "z3", name: "antioxidant", label: "mit Antioxidationsmittel" },
    { identifier: "z4", name: "flavorEnhancer", label: "mit Geschmacksverst\u00e4rker" },
    { identifier: "z5", name: "sulfured", label: "geschwefelt" },
    { identifier: "z6", name: "blackened", label: "geschw\u00e4rzt" },
    { identifier: "z7", name: "waxed", label: "gewachst" },
    { identifier: "z8", name: "phosphate", label: "mit Phosphat" },
    { identifier: "z9", name: "sweetener", label: "mit S\u00fc\u00dfungsmittel" },
    {
      identifier: "z12",
      name: "sourceOfPhenylalanine",
      label: "enth\u00e4lt eine Phenylalaninquelle",
    },
    {
      identifier: "z13",
      name: "laxative",
      label: "kann bei \u00fcberm\u00e4\u00dfigem Verzehr abf\u00fchrend wirken",
    },
    { identifier: "a1", name: "gluten", label: "glutenhaltiges Getreide" },
    { identifier: "a2", name: "crustaceans", label: "Krebstiere" },
    { identifier: "a3", name: "eggs", label: "Eier" },
    { identifier: "a4", name: "fish", label: "Fische" },
    { identifier: "a5", name: "peanut", label: "Erdn\u00fcsse" },
    { identifier: "a6", name: "soja", label: "Soja" },
    { identifier: "a7", name: "lactose", label: "Milch (einschlie\u00dflich Lactose)" },
    { identifier: "a8", name: "nuts", label: "Schalenfr\u00fcchte" },
    { identifier: "a9", name: "celery", label: "Sellerie" },
    { identifier: "a10", name: "mustard", label: "Senf" },
    { identifier: "a11", name: "sesame", label: "Sesamsamen" },
    { identifier: "a12", name: "sulfates", label: "Schwefeldioxid und Sulfite" },
    { identifier: "a13", name: "lupins", label: "Lupinen" },
    { identifier: "a14", name: "mollusks", label: "Weichtiere" },
    { identifier: "a15", name: "wheat", label: "Weizen" },
    { identifier: "a16", name: "rye", label: "Roggen" },
    { identifier: "a17", name: "barley", label: "Gerste" },
    { identifier: "a18", name: "oats", label: "Hafer" },
    { identifier: "a19", name: "almonds", label: "Mandeln" },
    { identifier: "a20", name: "hazelnuts", label: "Haseln\u00fcsse" },
    { identifier: "a21", name: "walnuts", label: "Waln\u00fcsse" },
    { identifier: "a22", name: "cashews", label: "Cashewn\u00fcsse" },
    { identifier: "a23", name: "pecans", label: "Pecann\u00fcsse" },
    { identifier: "a24", name: "brazilNuts", label: "Paran\u00fcsse" },
    { identifier: "a25", name: "pistachios", label: "Pistazien" },
    { identifier: "a26", name: "macadamiaNuts", label: "Macadamian\u00fcsse" },
    { identifier: "a27", name: "spelt", label: "Dinkel" },
    { identifier: "a28", name: "kamut", label: "Kamut" },
    { identifier: "a", name: "alcohol", label: "Alkohol" },
    { identifier: "k", name: "garlic", label: "Knoblauch" },
    { identifier: "vs", name: "shoulderOfHam", label: "Vorderschinken" },
    { identifier: "r", name: "beef", label: "Rind/Kalb" },
    { identifier: "s", name: "pork", label: "Schwein" },
    { identifier: "g", name: "poultry", label: "Gefl\u00fcgel" },
    { identifier: "f", name: "fish", label: "Fisch" },
    { identifier: "l", name: "lamb", label: "Lamm" },
    { identifier: "h", name: "rabbit", label: "Hase / Kaninchen" },
    { identifier: "w", name: "venison", label: "Wild" },
    { identifier: "v", name: "vegan", label: "Vegan" },
  ],
}
